def git_branch = '*/master'
def git_url = 'https://github.com/dreamjser/h5-react-template.git'

node {
   stage("checkout"){
    git credentialsId: '62f021ba-8227-49d0-b215-dd05595fe8fe', url: 'https://github.com/dreamjser/h5-react-template.git'


	}
	stage("build package"){
    sh """
      echo '1'
      ./build.sh
    """
	}
}
